const fs = require('fs');
const path = require('path');

const FILE_PATH = path.resolve(__dirname, '../../source-data/reference-results/branch-semester-credits.json');

const PDF_STRUCTURE = {
  "CAI": {
    "1-1": ["LINEAR ALGEBRA & CALCULUS", "INTRODUCTION TO PROGRAMMING", "ENGINEERING PHYSICS", "BASIC ELECTRICAL & ELECTRONICS ENGINEERING", "ENGINEERING GRAPHICS"],
    "1-2": ["DIFFERENTIAL EQUATIONS & VECTOR CALCULUS", "DATA STRUCTURES", "CHEMISTRY", "COMMUNICATIVE ENGLISH", "BASIC CIVIL & MECHANICAL ENGINEERING"],
    "2-1": ["DISCRETE MATHEMATICS & GRAPH THEORY", "UNIVERSAL HUMAN VALUES", "ADVANCED DATA STRUCTURES & ALGORITHMS", "OBJECT ORIENTED PROGRAMMING THROUGH JAVA", "ARTIFICIAL INTELLIGENCE"],
    "2-2": ["PROBABILITY & STATISTICS", "DATABASE MANAGEMENT SYSTEMS", "DIGITAL LOGIC AND COMPUTER ORGANIZATION", "MACHINE LEARNING", "OPTIMIZATION TECHNIQUES"],
    "3-1": ["OPERATING SYSTEMS", "COMPUTER NETWORKS", "INTERNET OF THINGS", "DEEP LEARNING", "ENTREPRENEURSHIP DEVELOPMENT & VENTURE CREATION"],
    "3-2": ["SOFTWARE ENGINEERING", "GENERATIVE A.I.", "DATA VISUALIZATION", "SOFTWARE TESTING METHODOLOGIES", "CLOUD COMPUTING", "DISASTER MANAGEMENT"]
  },
  "CSM": {
    "1-1": ["LINEAR ALGEBRA & CALCULUS", "INTRODUCTION TO PROGRAMMING", "ENGINEERING PHYSICS", "BASIC ELECTRICAL & ELECTRONICS ENGINEERING", "ENGINEERING GRAPHICS"],
    "1-2": ["DIFFERENTIAL EQUATIONS&VECTOR CALCULUS", "DATA STRUCTURES", "CHEMISTRY", "COMMUNICATIVE ENGLISH", "BASIC CIVIL&MECHANICAL ENGINEERING"],
    "2-1": ["UNIVERSAL HUMAN VALUES", "DISCRETE MATHEMATICS & GRAPH THEORY", "ADVANCED DATA STRUCTURES & ALGORITHMS", "OBJECT ORIENTED PROGRAMMING THROUGH JAVA", "ARTIFICIAL INTELLIGENCE"],
    "2-2": ["PROBABILITY & STATISTICS", "OPTIMIZATION TECHNIQUES", "DATABASE MANAGEMENT SYSTEMS", "MACHINE LEARNING", "DIGITAL LOGIC AND COMPUTER ORGANIZATION"],
    "3-1": ["ENTREPRENEURSHIP DEVELOPMENT & VENTURE CREATION", "INFORMATION RETRIEVAL SYSTEMS", "OPERATING SYSTEMS", "COMPUTER NETWORKS", "INTERNET OF THINGS"],
    "3-2": ["DISASTER MANAGEMENT", "SOFTWARE TESTING METHODOLOGIES", "NATURAL LANGUAGE PROCESSING", "DEEP LEARNING", "DATA VISUALIZATION", "NOSQL DATABASES"]
  },
  "CSD": {
    "1-1": ["LINEAR ALGEBRA & CALCULUS", "INTRODUCTION TO PROGRAMMING", "ENGINEERING PHYSICS", "BASIC ELECTRICAL & ELECTRONICS ENGINEERING", "ENGINEERING GRAPHICS"],
    "1-2": ["DIFFERENTIAL EQUATIONS&VECTOR CALCULUS", "DATA STRUCTURES", "CHEMISTRY", "COMMUNICATIVE ENGLISH", "BASIC CIVIL&MECHANICAL ENGINEERING"],
    "2-1": ["UNIVERSAL HUMAN VALUES", "DISCRETE MATHEMATICS & GRAPH THEORY", "ADVANCED DATA STRUCTURES & ALGORITHMS", "OBJECT ORIENTED PROGRAMMING THROUGH JAVA", "INTRODUCTION TO DATA SCIENCE"],
    "2-2": ["DATABASE MANAGEMENT SYSTEMS", "OPTIMIZATION TECHNIQUES", "STATISTICAL METHODS FOR DATA SCIENCE", "DATA ENGINEERING", "COMPUTER ORGANIZATION AND ARCHITECTURE"],
    "3-1": ["ENTREPRENEURSHIP DEVELOPMENT & VENTURE CREATION", "COMPUTER NETWORKS", "INTERNET OF THINGS", "MACHINE LEARNING", "SOFTWARE ENGINEERING"],
    "3-2": ["DISASTER MANAGEMENT", "DEEP LEARNING", "DATA VISUALIZATION", "NOSQL DATABASES", "OPERATING SYSTEMS", "CLOUD COMPUTING"]
  },
  "AID": {
    "1-1": ["LINEAR ALGEBRA & CALCULUS", "INTRODUCTION TO PROGRAMMING", "ENGINEERING PHYSICS", "BASIC ELECTRICAL & ELECTRONICS ENGINEERING", "ENGINEERING GRAPHICS"],
    "1-2": ["DIFFERENTIAL EQUATIONS&VECTOR CALCULUS", "DATA STRUCTURES", "CHEMISTRY", "COMMUNICATIVE ENGLISH", "BASIC CIVIL&MECHANICAL ENGINEERING"],
    "2-1": ["UNIVERSAL HUMAN VALUES", "DISCRETE MATHEMATICS & GRAPH THEORY", "ADVANCED DATA STRUCTURES AND ALGORITHMS", "OBJECT ORIENTED PROGRAMMING THROUGH JAVA", "DATABASE MANAGEMENT SYSTEMS"],
    "2-2": ["OPERATING SYSTEMS", "OPTIMIZATION TECHNIQUES", "SOFTWARE ENGINEERING", "STATISTICAL METHODS FOR DATA SCIENCE", "INTRODUCTION TO DATA SCIENCE"],
    "3-1": ["COMPUTER NETWORKS", "ENTREPRENEURSHIP DEVELOPMENT & VENTURE CREATION", "COMPUTER ORGANIZATION AND ARCHITECTURE", "INTERNET OF THINGS", "ARTIFICIAL INTELLIGENCE"],
    "3-2": ["DISASTER MANAGEMENT", "BIG DATA ANALYTICS", "NOSQL DATABASES", "MACHINE LEARNING", "DATA VISUALIZATION", "CLOUD COMPUTING"]
  },
  "CSC": {
    "1-1": ["LINEAR ALGEBRA & CALCULUS", "INTRODUCTION TO PROGRAMMING", "ENGINEERING PHYSICS", "BASIC ELECTRICAL & ELECTRONICS ENGINEERING", "ENGINEERING GRAPHICS"],
    "1-2": ["DIFFERENTIAL EQUATIONS&VECTOR CALCULUS", "DATA STRUCTURES", "CHEMISTRY", "COMMUNICATIVE ENGLISH", "BASIC CIVIL&MECHANICAL ENGINEERING"],
    "2-1": ["UNIVERSAL HUMAN VALUES", "OBJECT ORIENTED PROGRAMMING THROUGH JAVA", "DISCRETE MATHEMATICS & GRAPH THEORY", "DIGITAL LOGIC & COMPUTER ORGANIZATION", "ADVANCED DATA STRUCTURES & ALGORITHMS"],
    "2-2": ["OPERATING SYSTEMS", "MANAGERIAL ECONOMICS AND FINANCIAL ANALYSIS", "DATABASE MANAGEMENT SYSTEMS", "NUMBER THEORY & APPLICATIONS", "COMPUTER NETWORKS"],
    "3-1": ["ENTREPRENEURSHIP DEVELOPMENT & VENTURE CREATION", "CLOUD COMPUTING", "INTRODUCTION TO CYBER SECURITY", "AUTOMATA THEORY & COMPILER DESIGN", "INTERNET OF THINGS"],
    "3-2": ["DISASTER MANAGEMENT", "NATURAL LANGUAGE PROCESSING", "CRYPTOGRAPHY & NETWORK SECURITY", "SOFTWARE TESTING METHODOLOGIES", "MACHINE LEARNING", "CYBER CRIMES & DIGITAL FORENSICS"]
  }
};

const verifiedSets = {
    "CAI": ["1-2"],
    "CSM": ["1-1"],
    "CSD": ["1-2"],
    "AID": ["1-1"],
    "CSC": ["1-2"]
};

let existingData = {};
if (fs.existsSync(FILE_PATH)) {
    existingData = JSON.parse(fs.readFileSync(FILE_PATH));
}

const branches = ['CAI', 'CSM', 'CSD', 'AID', 'CSC'];
const semesters = ['1-1', '1-2', '2-1', '2-2', '3-1', '3-2'];

const newData = {};

for (const b of branches) {
    newData[b] = {};
    for (const s of semesters) {
        if (verifiedSets[b].includes(s) && existingData[b] && existingData[b][s] && existingData[b][s].length > 0) {
            // Keep the verified ones exactly as they are
            newData[b][s] = existingData[b][s];
        } else {
            // Unverified combination. Populate with known theories + missing credits
            const subjects = [];
            const theories = PDF_STRUCTURE[b][s] || [];
            
            for (const t of theories) {
                subjects.push({
                    subjectName: t,
                    credits: "MISSING",
                    type: "THEORY"
                });
            }
            
            // Add a placeholder block for unknown labs/activities to prompt the user
            subjects.push({
                subjectName: "MISSING_LAB_OR_ACTIVITY_RECORD",
                credits: "MISSING",
                type: "MISSING"
            });
            
            newData[b][s] = subjects;
        }
    }
}

fs.writeFileSync(FILE_PATH, JSON.stringify(newData, null, 2));
console.log("Template generated successfully.");
